"""initial schema

Revision ID: d7b8d039d5af
Revises: 
Create Date: 2026-08-18 21:07:51.521253

"""
from alembic import op
import sqlalchemy as sa


revision = 'd7b8d039d5af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('recovery_code_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('consent_152fz_at', sa.DateTime(), nullable=True),
    sa.Column('contact_note', sa.String(length=255), nullable=True),
    sa.Column('tg_chat_id', sa.String(length=64), nullable=True),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('game_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=False),
    sa.Column('account_id', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('profile_url', sa.String(length=300), nullable=True),
    sa.Column('rating_raw', sa.String(length=30), nullable=False),
    sa.Column('rating_ordinal', sa.Integer(), nullable=False),
    sa.Column('verify_status', sa.String(length=20), nullable=False),
    sa.Column('verified_raw', sa.String(length=30), nullable=True),
    sa.Column('verified_label', sa.String(length=60), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_roles', sa.JSON(), nullable=False),
    sa.Column('is_looking', sa.Boolean(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game', name='uq_profile_user_game')
    )
    op.create_index(op.f('ix_game_profiles_game'), 'game_profiles', ['game'], unique=False)
    op.create_index(op.f('ix_game_profiles_rating_ordinal'), 'game_profiles', ['rating_ordinal'], unique=False)
    op.create_index(op.f('ix_game_profiles_user_id'), 'game_profiles', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('tg_sent_at', sa.DateTime(), nullable=True),
    sa.Column('tg_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('contact_note', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_tokens_token_hash'), 'reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_reset_tokens_user_id'), 'reset_tokens', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating_min_wanted', sa.Integer(), nullable=True),
    sa.Column('rating_max_wanted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bumped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_bumped_at'), 'teams', ['bumped_at'], unique=False)
    op.create_index(op.f('ix_teams_captain_id'), 'teams', ['captain_id'], unique=False)
    op.create_index(op.f('ix_teams_game'), 'teams', ['game'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_team_id'), 'applications', ['team_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_status'), 'invites', ['status'], unique=False)
    op.create_index(op.f('ix_invites_team_id'), 'invites', ['team_id'], unique=False)
    op.create_index(op.f('ix_invites_user_id'), 'invites', ['user_id'], unique=False)
    op.create_table('team_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'role', name='uq_slot_team_role')
    )
    op.create_index(op.f('ix_team_slots_team_id'), 'team_slots', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_slots_team_id'), table_name='team_slots')
    op.drop_table('team_slots')
    op.drop_index(op.f('ix_invites_user_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_team_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_status'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_team_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_teams_game'), table_name='teams')
    op.drop_index(op.f('ix_teams_captain_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_bumped_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_reset_tokens_user_id'), table_name='reset_tokens')
    op.drop_index(op.f('ix_reset_tokens_token_hash'), table_name='reset_tokens')
    op.drop_table('reset_tokens')
    op.drop_table('reset_requests')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_game_profiles_user_id'), table_name='game_profiles')
    op.drop_index(op.f('ix_game_profiles_rating_ordinal'), table_name='game_profiles')
    op.drop_index(op.f('ix_game_profiles_game'), table_name='game_profiles')
    op.drop_table('game_profiles')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    # ### end Alembic commands ###
